### ISSUE TITLE
Github pages

### ISSUE THREAD

**Issue by rafaelcastrocouto** [Calada2/Minecraft#1]
Hi there! I loved ❤ this project gratz! 👏👏👏

I've created a gh-pages branch, that allow it to use github servers to play the game (https://rafaelcastrocouto.github.io/Minecraft/)

I've also done some simple coding adding some social head elements and I moved the JS and CSS to separate files (style.css and game.js)

I was going to make a pull request but I thought I should ask you first, since if your create the gh-pages branch we can avoid all the "moving between branches" git commands.

If you want me to work on something specific just tell, I'm at your service!

Cheers

**Comment by Calada2** [comment]
Hey! Glad you liked it! :)

Thanks for cleaning up the code and adding the meta tags! :D I created a pull request just now.
Feel free to add anything you'd like and thanks for the offer :) I'll let you know if I have something in mind
